### ISSUE TITLE
Change bgclr.txt into a config file 

### ISSUE THREAD

**Issue by nathan-a-macleod** [nathan-a-macleod/terminalEnv#8]
Would it be good to do this? The config file could then be used for all other settings in the future if needed. Then the colour could be replaced with 'COLOR: blue' or something similar. @RobiTheGit

**Comment by RobiTheGit** [comment]
This actually is a good idea, I'll get on it.

**Comment by nathan-a-macleod** [comment]
Thanks looks really great btw 👍
